spring:
  application:
    name: backend-citas-zuul
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8030


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8781/eureka

logging:
  file: logs/backend-citas-usuario.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
      
zuul:
  routes:
    usuario.serviceId : backend-citas-usuario
    usuario.path : /api/usuario/**
        
    seguridad.serviceId : backend-citas-seguridad
    seguridad.path : /api/seguridad/**
    seguridad.sensitiveHeaders: Cookie,Set-Cookie
 